# Generated by Django 5.1.7 on 2025-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order prosesing', 'Order prosesing'), ('Order Complite', 'Order Complite'), ('Order Canceled', 'Order Canceled'), ('Order Reseived', 'Order Reseived'), ('Order On theway', 'Order On theway')], default='Order Reseived', max_length=130),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
